[workspace]
resolver = "3"
members = ["term", "core", "desktop", "doctor"]
default-members = [
    "desktop",
    "term",
]

[workspace.package]
publish = false

[workspace.dependencies]

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package."gbemu-core"]
opt-level = 1
