[package]
name = "gbemu-term"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
gbemu-core = { path = "../core" }

env_logger = "0.11"
dotenv = "0.15"
crossterm = "0.29"
ratatui = "0.30"
clap = { version = "4.5", features = ["derive"] }
log = "0.4"
