[package]
name = "gbemu-core"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bitflags = "2.9"
log = "0.4"
paste = "1.0"
zip = { version = "6.0", default-features = false, features = ["deflate"] }

[features]
test-bus = []
use-test-roms = []